Repository noigamegun/codekit, pull requests merged in 2025-05, with the labels that each got.

#10 Add Dev Google Login
  login.html
Labels: size/M

#11 Win's Changes
  win/about.html
  win/contact.html
  win/index.html
  win/indexself.html
  win/style.css
Labels: size/L

#12 Moved to old folder.
  old/about.html
  old/index.html
  old/login.html
  old/solutions.html
  old/styleAbout.css
  old/styleSolutions.css
Labels: size/XS

#13 Restore README.md to old directory
  old/README.md
Labels: size/XS
